version: "2.1"
services:
  openvpn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Saigon
      - INTERFACE=eth0
    #volumes:
    #  - ./config:/config
    ports:
      - 811:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
